name: MacOS

on: pull_request

jobs:
  build:
    name: Building with ${{ matrix.sofa_version }}
    runs-on: macos-10.15
    strategy:
      matrix:
        sofa_version: [ v20.06.01 ]
    env:
      SOFA_VERSION: ${{ matrix.sofa_version }}
      SOFA_ROOT: /opt/sofa

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install requirements
        run: |
          brew install ccache eigen
          python3 -m pip install numpy

      - name: Install pybind11
        run: |
          git clone --depth 1 -b v2.4  https://github.com/pybind/pybind11.git /tmp/pybind11
          cmake -S/tmp/pybind11 -B/tmp/pybind11/build -DPYBIND11_TEST=OFF -DCMAKE_BUILD_TYPE=Release
          sudo cmake --install /tmp/pybind11/build
          rm -rf /tmp/pybind11

      - name: cache boost
        uses: actions/cache@v2
        id: cache-boost
        with:
          path: /opt/boost
          key: boost-1.67.0-macos-1015
          restore-keys: boost-macos-10-15

      - name: Download boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          curl --output boost.tar.gz -L "https://boostorg.jfrog.io/artifactory/main/release/1.67.0/source/boost_1_67_0.tar.gz"
          tar xzf boost.tar.gz
      - name: Patch boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
            curl --output a.patch -L "https://github.com/boostorg/build/commit/b3a59d265929a213f02a451bb63cea75d668a4d9.patch?full_index=1"
            git apply -v --directory=boost_1_67_0/tools/build a.patch
            curl --output b.patch -L "https://gist.githubusercontent.com/jnbrunet/d9537ff8679b2b35976356f11f334777/raw/8d2a2a1e46d13064c2e18c5caa229b9b81933285/6e14ca24.patch"
            patch -d boost_1_67_0 boost/atomic/detail/ops_gcc_x86_dcas.hpp < b.patch
      - name: Build boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          cd boost_1_67_0
          ./bootstrap.sh --prefix=/opt/boost --without-libraries=python,mpi,log --without-icu --libdir=/opt/boost/lib -with-toolset=darwin
          sudo ./b2 toolset=darwin cxxflags=-std=c++11 link=shared threading=multi,single --layout=tagged -d0 -q variant=release architecture=x86 install

      - name: Download SOFA Release
        run:  |
          if [ "$SOFA_VERSION" = "master" ]; then
              curl --output sofa.zip -L "https://ci.inria.fr/sofa-ci-dev/job/nightly-generate-binaries-v20.12/lastSuccessfulBuild/CI_SCOPE=binaries_standard/artifact/MacOS/*zip*/MacOS.zip"
          else
              curl --output sofa.zip -L "https://github.com/sofa-framework/sofa/releases/download/v20.12.02/SOFA_v20.12.02_MacOS.zip"
          fi
          unzip sofa.zip -d temp
          sudo mv temp/`ls temp` $SOFA_ROOT

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'

      - name: ccache cache files
        uses: actions/cache@v2
        if: ${{ always() }}
        with:
          path: .ccache
          key: macos-ccache-${{ steps.time.outputs.time }}
          restore-keys: |
            macos-ccache-

      - name: cache MKL
        uses: actions/cache@v2
        id: cache-mkl
        with:
          path: /opt/intel
          key: mkl-macos-10-15

      - name: Install MKL
        if: steps.cache-mkl.outputs.cache-hit != 'true'
        run: |
          URL=https://registrationcenter-download.intel.com/akdlm/irc_nas/17714/m_BaseKit_p_2021.2.0.2855_offline.dmg
          curl --output /tmp/intel_mkl.dmg --url "$URL" --retry 5 --retry-delay 5
          hdiutil attach /tmp/intel_mkl.dmg
          sudo /Volumes/"$(basename "$URL" .dmg)"/bootstrapper.app/Contents/MacOS/bootstrapper -s --action install --eula=accept --continue-with-optional-error=yes --log-dir=.
          hdiutil detach /Volumes/"$(basename "$URL" .dmg)" -quiet

      - name: Build caribou
        env:
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 6
          CCACHE_MAXSIZE: "500M"
        run:
          export CCACHE_BASEDIR=$GITHUB_WORKSPACE &&
          export CCACHE_DIR=$GITHUB_WORKSPACE/.ccache &&
          ccache -z &&
          cmake
          -DBOOST_ROOT=/opt/boost
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          -DCARIBOU_BUILD_TESTS=ON
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=SofaCaribou
          .
          && make && make install
          && tar czvf SofaCaribou.tar.gz SofaCaribou
          && echo ${CCACHE_BASEDIR}
          && ccache -s

      - name: Archive production
        uses: actions/upload-artifact@v2
        with:
          name: caribou_macos_${{ matrix.sofa_version }}
          path: SofaCaribou.tar.gz
